#YAML
working_dir: /media/ivan/Диск/WAV2VEC_WD
output_dir: /media/ivan/Диск/WAV2VEC_OUTPUT
logs_to_db: True # False
logs_db_path: /media/ivan/Диск/WAV2VEC_DB # set path where to store SQLite DB if logs_to_db = True| else None
